# Generated by Django 6.0.4 on 2026-05-02 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_notaventa_empleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notaventa',
            name='usuario',
        ),
    ]
