# Generated by Django 6.0.4 on 2026-05-03 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_alter_empleado_estado_civil_and_more'),
        ('productos', '0003_alter_categoriaproducto_id_and_more'),
        ('ventas', '0004_remove_notaventa_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_venta', to='productos.producto'),
        ),
        migrations.AlterField(
            model_name='notaventa',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_venta', to='ventas.cliente'),
        ),
        migrations.AlterField(
            model_name='notaventa',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_venta', to='empleados.empleado'),
        ),
    ]
