# Generated by Django 6.0.4 on 2026-05-03 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_alter_empleado_id_alter_estadocivil_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='estado_civil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='empleados.estadocivil'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nacionalidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='empleados.nacionalidad'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='tipo_contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='empleados.tipocontrato'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='empleados.turno'),
        ),
    ]
