# Generated by Django 5.2.6 on 2026-04-26 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_movimientoinventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaproducto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
